package com.miaosha.project.dao;

import com.miaosha.project.dataobject.ItemDO;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jul 08 12:11:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jul 08 12:11:59 CST 2022
     */
    int insert(ItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jul 08 12:11:59 CST 2022
     */
    int insertSelective(ItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jul 08 12:11:59 CST 2022
     */
    ItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jul 08 12:11:59 CST 2022
     */
    int updateByPrimaryKeySelective(ItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Fri Jul 08 12:11:59 CST 2022
     */
    int updateByPrimaryKey(ItemDO row);
}